### ISSUE TITLE
Logical error in "2016-01-6-Swift-One-Liners-Playground" file

### ISSUE THREAD

**Issue by mjhassan** [uraimo/Swift-Playgrounds#2]
On prime number generation using **Sieve of Erathostenes**,  you wrote:
    
    //:#10 Sieve of Erathostenes
    
    // With Side-effects
    var n = 50
    var primes = Set(2...n)
    
    
    (2...Int(sqrt(Double(n)))).forEach{
         primes.subtract(Set(stride(from:2*$0, to:n, by:$0)))
    }
    primes.sorted()
    
    
    // Without Side-effects
    var sameprimes = Set(2...n) 
    
    sameprimes.subtract(Set(2...Int(sqrt(Double(n)))) 
                       .flatMap{stride(from:2*$0, to:n, by:$0)}) 
    sameprimes.sorted()

which gives
> [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 50]

number 50 shouldn't be here. And this is because of `stride`. 

According to apples [documentation](https://developer.apple.com/documentation/swift/1641347-stride) `stride` excludes the end. Therefore, `subtract` fails to eliminate 50 from prime set.

Please fix the code by including last element in the subtraction sequence. One possible solution is: 

    
    sameprimes.subtract(Set(2...Int(sqrt(Double(n)))) 
                       .flatMap{stride(from:2*$0, to:n+1, by:$0)})

**Comment by uraimo** [comment]
Thanks for pointing this out!
The playground was originally created for Swift 2.2 and this error is the result of a small Swift change happened in 3.0.
Previously, the stride method was part of the Strideable protocol and returned `the sequence of values (self, self + stride, self + stride + stride, ... last) where last is the last value in the progression less than or equal to end`, this was later modified as you describe.
